name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://stockly-ai.streamlit.app/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deployment marker
        run: echo "App deployed to Streamlit"
